### ISSUE TITLE
not listed on the MDAnalysis "Used by" page

### ISSUE THREAD

**Issue by orbeckst** [GMPavanLab/Swarm-CG#10]
Hello,

If you would like Swarm-CG to appear in the https://www.mdanalysis.org/pages/used-by/ page then please open an issue in https://github.com/MDAnalysis/MDAnalysis.github.io/issues with all relevant information or directly open a PR. We'd be happy to include you!

— @orbeckst

**Comment by CharlyEmpereurmot** [comment]
Thank you for suggesting!
