### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'gmx_cmd'

### ISSUE THREAD

**Issue by mikeboyle321** [GMPavanLab/Swarm-CG#17]
Hello,

I'm running into a pesky AttributeError: 'Namespace' object has no attribute 'gmx_cmd' when running scg_optimize on a polymer I am trying to map using your program.

It seems everything is running smoothly until the minimization step, but then an error is triggered when it tries run the equilibration step of the first CG iteration. I attached my input and output files here. I didn't include the atomistic trajectory as the file is large, and I think this might be a bug on the cg-swarm side given that the minimization runs fine and this is a python based error. If you need the trajectory to reproduce the error, let me know and I can drop a google drive link here.

I use slurm to run the bash script 'cg-swarm-run' in the zip file below. I think if you look there first, the rest of the files should be arranged according to your example.

[cg_swarm_testing(2).zip](https://github.com/GMPavanLab/Swarm-CG/files/5759633/cg_swarm_testing.2.zip)

Please let me know if I made a mistake anywhere!

Cheers,
Mike Boyle

**Comment by mikeboyle321** [comment]
A quick update:

I retried running everything this morning without the mpi commands. specifically, I replaced:

"scg_optimize -in_dir exp_01/ -gmx gmx_mpi -mpi 3 -out_dir angle_function_2/"

with

"scg_optimize -in_dir exp_01/ -gmx gmx -out_dir angle_function_2/"

It is running without issues now, and looks like it is utilizing all the gpus and cpus available. So maybe the error I encountered is related to the mpi argument parsing?

I hope that helps.

Cheers,
Mike
 
P.S. This program is awesome!! Thank you for writing and publishing it! I can't wait to see the results of the first run.

**Comment by mikeboyle321** [comment]
The issue is in line 1440 of swarmCG.py

Incorrect reference of _gmx_cmd_ as object of the input arguments _ns_:
gmx_cmd = f"mpirun -np {ns.mpi_tasks} {ns.gmx_cmd}"

Correcting to 
gmx_cmd = f"mpirun -np {ns.mpi_tasks} {gmx_cmd}"

resolves the issue and allows MPI gmx calls.

I hope that helps.

Cheers,
Mike Boyle

**Comment by giovannidoni** [comment]
Hi Mike, thank you very much for you input. I am in the process of refactoring a bit the code starting from the simulation execution. I am going to integrate this fix asap in the new implementation! Cheers
