### ISSUE TITLE
Constraints optimization

### ISSUE THREAD

**Issue by MaksimKalutskiy** [GMPavanLab/Swarm-CG#41]
Dear Swarm-CG creators, 
First of all, great project!
I have issue with constraints optimization. The addition of constraints into the itp file always crushes the optimization with the following error:

`-- ! ERROR ! --
In the provided CG ITP file constraints have been grouped, but constraints group 1 holds lines that have different parameters.
Parameters should be identical within a group, only CG beads IDs should differ.
Please correct the CG ITP file and separate groups using a blank or commented line.
`

But all parameters inside the group are identical in my itp file, moreover even addition only one bond constraint results in the same error.  Without any constraint all works perfectly fine.

[itp_file.zip](https://github.com/GMPavanLab/Swarm-CG/files/6060333/itp_file.zip)

**Comment by CharlyEmpereurmot** [comment]
Dear Maksim,

Indeed your ITP looks fine. This is clearly a small bug in the code, we had constraints tuning working as fine as for the bonds.

I will have a look ASAP, thank you for reporting!

**Comment by CharlyEmpereurmot** [comment]
Please try to update to version 1.2.5, hopefully it will solve your problem

**Comment by MaksimKalutskiy** [comment]
Yep, its working. 
Thank you for dealing with this issue and for fast reply!
